repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.3.0
    hooks:
      - id: editorconfig-checker
